name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'
      - '**.json'

jobs:
  acc-tests:
    runs-on: [self-hosted,tfmodule]
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - name: e2e test
        run: |
          PATH=$PATH:/go/bin:/usr/local/go/bin make e2e-test
      - name: version upgrade test
        run: |
          PATH=$PATH:/go/bin:/usr/local/go/bin make version-upgrade-test