name: E2E Test
on:
  pull_request:
    types: [ 'opened', 'synchronize' ]
    paths:
      - '.github/**'
      - '**.go'
      - '**.tf'
      - '.github/workflows/**'
      - '**.md'
      - '**.json'

jobs:
  acc-tests:
    runs-on: ubuntu-latest
    environment:
      name: acctests
    steps:
      - uses: actions/checkout@v3
      - uses: actions/setup-go@v3
        with:
          go-version: '>=1.17.0'
      - uses: hashicorp/setup-terraform@v2
        with:
          terraform_version: 1.1.9
          terraform_wrapper: false
      - name: make tools
        run: |
          make tools
      - name: e2e test
        run: |
          make e2e-test
      - name: version upgrade test
        run: |
          make version-upgrade-test